2018-11-19 16:56:58 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6) (retrying in 3 seconds)
2018-11-19 16:57:01 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6) (retrying in 3 seconds)
2018-11-19 16:57:04 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6) (retrying in 3 seconds)
2018-11-19 16:57:07 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6) (retrying in 3 seconds)
2018-11-19 16:57:10 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6) (retrying in 3 seconds)
2018-11-19 16:57:13 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6) (retrying in 3 seconds)
2018-11-19 16:57:16 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6) (retrying in 3 seconds)
2018-11-19 16:57:19 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6) (retrying in 3 seconds)
2018-11-19 16:57:22 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6) (retrying in 3 seconds)
2018-11-19 16:57:25 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6) (retrying in 3 seconds)
2018-11-19 16:57:25 ERROR (MainThread) [homeassistant.setup] Setup failed for recorder: Component failed to initialize.
2018-11-19 16:57:25 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of history. Setup failed for dependencies: recorder
2018-11-19 16:57:25 ERROR (MainThread) [homeassistant.setup] Setup failed for history: Could not set up all dependencies.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of logbook. Setup failed for dependencies: recorder
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Setup failed for logbook: Could not set up all dependencies.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Setup failed for mqtt: Component failed to initialize.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of history_graph. Setup failed for dependencies: history
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Setup failed for history_graph: Could not set up all dependencies.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of sensor.mqtt. Setup failed for dependencies: mqtt
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.mqtt: Could not set up all dependencies.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of sensor.mqtt. Setup failed for dependencies: mqtt
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.mqtt: Could not set up all dependencies.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of sensor.mqtt. Setup failed for dependencies: mqtt
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.mqtt: Could not set up all dependencies.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of sensor.mqtt. Setup failed for dependencies: mqtt
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.mqtt: Could not set up all dependencies.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OnHub for upnp
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/config_entries.py", line 244, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/app/homeassistant/components/upnp/__init__.py", line 143, in async_setup_entry
    await device.async_add_port_mappings(ports, local_ip)
  File "/usr/src/app/homeassistant/components/upnp/device.py", line 66, in async_add_port_mappings
    internal_port)
  File "/usr/src/app/homeassistant/components/upnp/device.py", line 87, in _async_add_port_mapping
    lease_duration=None)
  File "/usr/local/lib/python3.6/site-packages/async_upnp_client/igd.py", line 219, in async_add_port_mapping
    await action.async_call(
AttributeError: 'NoneType' object has no attribute 'async_call'
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of switch.mqtt. Setup failed for dependencies: mqtt
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.mqtt: Could not set up all dependencies.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of switch.mqtt. Setup failed for dependencies: mqtt
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.mqtt: Could not set up all dependencies.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of switch.mqtt. Setup failed for dependencies: mqtt
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.mqtt: Could not set up all dependencies.
2018-11-19 16:57:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of switch.mqtt. Setup failed for dependencies: mqtt
2018-11-19 16:57:27 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.mqtt: Could not set up all dependencies.
2018-11-19 16:57:27 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OnHub for upnp
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/config_entries.py", line 244, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/app/homeassistant/components/upnp/__init__.py", line 143, in async_setup_entry
    await device.async_add_port_mappings(ports, local_ip)
  File "/usr/src/app/homeassistant/components/upnp/device.py", line 66, in async_add_port_mappings
    internal_port)
  File "/usr/src/app/homeassistant/components/upnp/device.py", line 87, in _async_add_port_mapping
    lease_duration=None)
  File "/usr/local/lib/python3.6/site-packages/async_upnp_client/igd.py", line 219, in async_add_port_mapping
    await action.async_call(
AttributeError: 'NoneType' object has no attribute 'async_call'
2018-11-19 16:57:27 ERROR (SyncWorker_20) [homeassistant.components.sensor.xbox_live] Can't setup XboxAPI connection. Check your account or  api key on xboxapi.com. Code: 500 Description: A new login is required to get fresh access tokens 
2018-11-19 16:57:30 ERROR (SyncWorker_11) [homeassistant.components.light.yeelight] Failed to connect to bulb 192.168.87.56, Family Room Lamp: A socket error occurred when sending the command.
2018-11-19 16:57:32 ERROR (SyncWorker_7) [homeassistant.components.dyson] Unable to connect to device NetworkDevice(name=Office Hot+Cool,address=192.168.87.127,port=1883): [Errno 113] No route to host
